apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tzytzytzy/otot-a:latest
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 40m